// <auto-generated />
using System;
using System.Collections.Generic;
using Embe.C2C.Infrastructure.Ef.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Embe.C2C.Infrastructure.Migrations
{
    [DbContext(typeof(C2CContext))]
    [Migration("20260712112405_AspNetUserDomainUserCascadeDelete")]
    partial class AspNetUserDomainUserCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Balance", "Embe.C2C.Domain.Aggregates.Accounts.Account.Balance#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "Embe.C2C.Domain.Aggregates.Accounts.Account.Balance#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Blockings.Blocking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockerUserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("BlockerUserId");

                    b.ToTable("Blockings");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Candidates.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateSearchProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateUserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSearchProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CandidateSearchProfileId");

                    b.HasIndex("CandidateUserId");

                    b.HasIndex("UserSearchProfileId");

                    b.HasIndex("UserId", "CandidateUserId", "UserSearchProfileId", "CandidateSearchProfileId")
                        .IsUnique();

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Judgements.Judgement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("boolean");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.ToTable("Judgements");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Matchings.Matching", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId1SearchProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId2")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId2SearchProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId1SearchProfileId");

                    b.HasIndex("UserId2");

                    b.HasIndex("UserId2SearchProfileId");

                    b.ToTable("Matchings");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsReply")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ReplyToMessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ReadAt");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("Notifications");

                    b.HasDiscriminator<string>("NotificationType").HasValue("Notification");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.SearchProfiles.SearchProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("AgeRangeMax")
                        .HasColumnType("integer");

                    b.Property<int?>("AgeRangeMin")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("MaximumDistance")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Engagement", "Embe.C2C.Domain.Aggregates.SearchProfiles.SearchProfile.Engagement#Engagement", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Boundedness")
                                .HasColumnType("integer");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date");

                            b1.Property<int>("Frequency")
                                .HasColumnType("integer");

                            b1.Property<int>("Medium")
                                .HasColumnType("integer");

                            b1.Property<DateOnly?>("StartDate")
                                .HasColumnType("date");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SearchProfiles");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Embe.C2C.Domain.Aggregates.Transactions.Transaction.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Currency", "Embe.C2C.Domain.Aggregates.Transactions.Transaction.Amount#Money.Currency#Currency", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Symbol")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Point>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Coordinates");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Coordinates"), "GIST");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.ToTable("DomainUsers");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchingId")
                        .HasColumnType("uuid");

                    b.Property<long>("MessageCount")
                        .HasColumnType("bigint");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId2")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LastMessageId")
                        .IsUnique();

                    b.HasIndex("MatchingId")
                        .IsUnique();

                    b.ToTable("Conversation");
                });

            modelBuilder.Entity("Embe.C2C.Infrastructure.Ef.Entities.AdminArea", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EngType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Point");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Point"), "GIST");

                    b.ToTable("AdminAreas");
                });

            modelBuilder.Entity("Embe.C2C.Infrastructure.Ef.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Embe.C2C.Infrastructure.Identity.MyIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Notifications.Matchings.MatchingNotification", b =>
                {
                    b.HasBaseType("Embe.C2C.Domain.Aggregates.Notifications.Notification");

                    b.Property<Guid>("MatchingId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartnerProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("PartnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartnerUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("MatchingId");

                    b.HasIndex("PartnerUserId");

                    b.HasDiscriminator().HasValue("MatchingNotification");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Notifications.Matchings.MatchingCreated", b =>
                {
                    b.HasBaseType("Embe.C2C.Domain.Aggregates.Notifications.Matchings.MatchingNotification");

                    b.HasDiscriminator().HasValue("MatchingCreated");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Notifications.Matchings.MatchingRemoved", b =>
                {
                    b.HasBaseType("Embe.C2C.Domain.Aggregates.Notifications.Matchings.MatchingNotification");

                    b.HasDiscriminator().HasValue("MatchingRemoved");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Accounts.Account", b =>
                {
                    b.HasOne("Embe.C2C.Domain.Aggregates.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Embe.C2C.Domain.Aggregates.Accounts.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Blockings.Blocking", b =>
                {
                    b.HasOne("Embe.C2C.Domain.Aggregates.Users.User", null)
                        .WithMany("BlockedBy")
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Embe.C2C.Domain.Aggregates.Users.User", null)
                        .WithMany("Blocked")
                        .HasForeignKey("BlockerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Candidates.Candidate", b =>
                {
                    b.HasOne("Embe.C2C.Domain.Aggregates.SearchProfiles.SearchProfile", "CandidateSearchProfile")
                        .WithMany()
                        .HasForeignKey("CandidateSearchProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Embe.C2C.Domain.Aggregates.Users.User", "CandidateUser")
                        .WithMany("CandidateCandidates")
                        .HasForeignKey("CandidateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Embe.C2C.Domain.Aggregates.Users.User", "User")
                        .WithMany("CandidateUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Embe.C2C.Domain.Aggregates.SearchProfiles.SearchProfile", "UserSearchProfile")
                        .WithMany()
                        .HasForeignKey("UserSearchProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateSearchProfile");

                    b.Navigation("CandidateUser");

                    b.Navigation("User");

                    b.Navigation("UserSearchProfile");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Judgements.Judgement", b =>
                {
                    b.HasOne("Embe.C2C.Domain.Aggregates.Candidates.Candidate", "Candidate")
                        .WithOne("Judgement")
                        .HasForeignKey("Embe.C2C.Domain.Aggregates.Judgements.Judgement", "CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Matchings.Matching", b =>
                {
                    b.HasOne("Embe.C2C.Domain.Aggregates.Users.User", "User1")
                        .WithMany("Matchings1")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Embe.C2C.Domain.Aggregates.SearchProfiles.SearchProfile", "User1SearchProfile")
                        .WithMany("MatchingsUserId1")
                        .HasForeignKey("UserId1SearchProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Embe.C2C.Domain.Aggregates.Users.User", "User2")
                        .WithMany("Matchings2")
                        .HasForeignKey("UserId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Embe.C2C.Domain.Aggregates.SearchProfiles.SearchProfile", "User2SearchProfile")
                        .WithMany("MatchingsUserId2")
                        .HasForeignKey("UserId2SearchProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User1");

                    b.Navigation("User1SearchProfile");

                    b.Navigation("User2");

                    b.Navigation("User2SearchProfile");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Messages.Message", b =>
                {
                    b.HasOne("Embe.C2C.Domain.Aggregates.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Embe.C2C.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Embe.C2C.Domain.Aggregates.Messages.Message", "ReplyToMessage")
                        .WithMany()
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Conversation");

                    b.Navigation("ReplyToMessage");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Notifications.Notification", b =>
                {
                    b.HasOne("Embe.C2C.Domain.Aggregates.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.SearchProfiles.SearchProfile", b =>
                {
                    b.HasOne("Embe.C2C.Domain.Aggregates.Users.User", "User")
                        .WithMany("SearchProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Embe.C2C.Domain.Entities.SearchProfiles.SearchProfileGender", "_genders", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Gender")
                                .HasColumnType("integer");

                            b1.Property<uint>("RowVersion")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("xid")
                                .HasColumnName("xmin");

                            b1.Property<Guid>("SearchProfileId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SearchProfileId");

                            b1.ToTable("SearchProfileGender");

                            b1.WithOwner()
                                .HasForeignKey("SearchProfileId");
                        });

                    b.Navigation("User");

                    b.Navigation("_genders");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Transactions.Transaction", b =>
                {
                    b.HasOne("Embe.C2C.Domain.Aggregates.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Users.User", b =>
                {
                    b.HasOne("Embe.C2C.Infrastructure.Identity.MyIdentityUser", null)
                        .WithOne()
                        .HasForeignKey("Embe.C2C.Domain.Aggregates.Users.User", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Embe.C2C.Domain.Entities.Image", "_images", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("MarkedForDeletionAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("OwnerUserId")
                                .HasColumnType("uuid");

                            b1.Property<uint>("RowVersion")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("xid")
                                .HasColumnName("xmin");

                            b1.HasKey("Id");

                            b1.HasIndex("OwnerUserId");

                            b1.ToTable("Image");

                            b1.WithOwner()
                                .HasForeignKey("OwnerUserId");

                            b1.OwnsOne("Embe.C2C.Domain.ValueObjects.ImageDetails", "ImageDetails", b2 =>
                                {
                                    b2.Property<Guid>("ImageId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("MimeType")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("Order")
                                        .HasColumnType("integer");

                                    b2.HasKey("ImageId");

                                    b2.ToTable("Image");

                                    b2.WithOwner()
                                        .HasForeignKey("ImageId");
                                });

                            b1.Navigation("ImageDetails")
                                .IsRequired();
                        });

                    b.Navigation("_images");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Embe.C2C.Domain.Aggregates.Messages.Message", "LastMessage")
                        .WithOne()
                        .HasForeignKey("Embe.C2C.Domain.Entities.Conversation", "LastMessageId");

                    b.HasOne("Embe.C2C.Domain.Aggregates.Matchings.Matching", "Matching")
                        .WithOne("Conversation")
                        .HasForeignKey("Embe.C2C.Domain.Entities.Conversation", "MatchingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastMessage");

                    b.Navigation("Matching");
                });

            modelBuilder.Entity("Embe.C2C.Infrastructure.Ef.Entities.AdminArea", b =>
                {
                    b.HasOne("Embe.C2C.Infrastructure.Ef.Entities.AdminArea", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Embe.C2C.Infrastructure.Ef.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Embe.C2C.Domain.Aggregates.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Embe.C2C.Infrastructure.Identity.MyIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Embe.C2C.Infrastructure.Identity.MyIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Embe.C2C.Infrastructure.Identity.MyIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Embe.C2C.Infrastructure.Identity.MyIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Notifications.Matchings.MatchingNotification", b =>
                {
                    b.HasOne("Embe.C2C.Domain.Aggregates.Matchings.Matching", null)
                        .WithMany()
                        .HasForeignKey("MatchingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Embe.C2C.Domain.Aggregates.Users.User", null)
                        .WithMany()
                        .HasForeignKey("PartnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Candidates.Candidate", b =>
                {
                    b.Navigation("Judgement");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Matchings.Matching", b =>
                {
                    b.Navigation("Conversation")
                        .IsRequired();
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.SearchProfiles.SearchProfile", b =>
                {
                    b.Navigation("MatchingsUserId1");

                    b.Navigation("MatchingsUserId2");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Aggregates.Users.User", b =>
                {
                    b.Navigation("Blocked");

                    b.Navigation("BlockedBy");

                    b.Navigation("CandidateCandidates");

                    b.Navigation("CandidateUsers");

                    b.Navigation("Matchings1");

                    b.Navigation("Matchings2");

                    b.Navigation("SearchProfiles");
                });

            modelBuilder.Entity("Embe.C2C.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
