import type { Metadata } from "next";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { calSans } from "@/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({
  children,
}: RootLayoutProps) {

  return (

    <html
      lang="en"
    >

      <body className={`flex flex-col bg-(--color-primary) justify-between h-dvh w-dvw p-3 ${calSans.variable}`}>

        <Header />
        <main className="grow w-full h-full">{children}</main>
        <Footer />

      </body>

    </html>

  );

}