import type { Metadata } from "next";
import { calSans } from "@/fonts";

import "./globals.css";
import { Footer } from "../shared/components/footer/Footer";
import { getAuthenticatedUser } from "../shared/user";
import Surface from "../shared/components/surfaces/Surface";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type RootLayoutProps = {
  children: React.ReactNode;
};

export default async function RootLayout({
  children,
}: RootLayoutProps) {

  const user = await getAuthenticatedUser();

  return (

    <html
      lang="en"
    >

      <Surface as="body" className={`fs-group-primary flex flex-col justify-between h-dvh w-dvw px-2 pb-2 ${calSans.variable} gap-2`} variant="primary" padding="none">

        <main className="grow-1 overflow-y-scroll scrollbar-none">
          {children}
        </main>
        <Footer className="grow-0" user={user} />

      </Surface>

    </html>

  );

}