import type { Metadata } from "next";
import { calSans } from "@/fonts";

import "./globals.css";
import { Footer } from "../shared/components/footer/Footer";
import { getAuthenticatedUser } from "../shared/user";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type RootLayoutProps = {
  children: React.ReactNode;
};

export default async function RootLayout({
  children,
}: RootLayoutProps) {

  const user = await getAuthenticatedUser();

  return (

    <html
      lang="en"
    >

      <body className={`flex flex-col justify-between h-dvh w-dvw p-3 ${calSans.variable} gap-2`}>

        <main className="grow w-full h-full overflow-y-scroll scrollbar-none">{children}</main>
        <Footer user={user} />

      </body>

    </html>

  );

}